blank_issues_enabled: false
contact_links:
  - name: â“ Have a question or need help?
    url: https://github.com/lunchbreakdev/lbd-components/discussions
    about: >
      Have a question about the way LBD Components work?
      Or not sure if you're doing something right?
      Ask us over on the discussions
